apiVersion: v1
kind: Service
metadata:
  name: dotnet-hello-world-external-rollouts
spec:
  type: NodePort
  selector:
    app: dotnet-hello-world-rollouts
  ports:
  - name: http
    port: 80
    targetPort: 8080
