apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dotnet-hello-world-rollouts
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dotnet-hello-world-rollouts
  template:
    metadata:
      labels:
        app: dotnet-hello-world-rollouts
    spec:
      containers:
      - name: server
        image: aryanmohan/dotnet-argo-demo:2.0.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
